"use client";

import { useTranslations } from "next-intl";
import { Input } from "@inkloom/ui/input";
import { Label } from "@inkloom/ui/label";
import { Textarea } from "@inkloom/ui/textarea";

interface SeoSettingsProps {
  ogTitle: string;
  ogDescription: string;
  twitterCard: "summary" | "summary_large_image";
  robotsTxtCustom: string;
  onOgTitleChange: (value: string) => void;
  onOgDescriptionChange: (value: string) => void;
  onTwitterCardChange: (value: "summary" | "summary_large_image") => void;
  onRobotsTxtCustomChange: (value: string) => void;
}

export function SeoSettings({
  ogTitle,
  ogDescription,
  twitterCard,
  robotsTxtCustom,
  onOgTitleChange,
  onOgDescriptionChange,
  onTwitterCardChange,
  onRobotsTxtCustomChange,
}: SeoSettingsProps) {
  const t = useTranslations("settings");
  return (
    <div className="space-y-6">
      <div className="space-y-4">
        <div>
          <Label className="text-sm font-medium">{t("seoConfig.openGraphDefaults")}</Label>
          <p className="text-xs text-muted-foreground mt-1">
            {t("seoConfig.openGraphDescription")}
          </p>
        </div>

        <div className="space-y-3">
          <div className="space-y-2 max-w-md">
            <Label htmlFor="ogTitle" className="text-xs">{t("seoConfig.ogTitle")}</Label>
            <Input
              id="ogTitle"
              value={ogTitle}
              onChange={(e) => onOgTitleChange(e.target.value)}
              placeholder={t("seoConfig.ogTitlePlaceholder")}
            />
          </div>

          <div className="space-y-2">
            <Label htmlFor="ogDescription" className="text-xs">{t("seoConfig.ogDescription")}</Label>
            <Textarea
              id="ogDescription"
              value={ogDescription}
              onChange={(e) => onOgDescriptionChange(e.target.value)}
              placeholder={t("seoConfig.ogDescriptionPlaceholder")}
              rows={2}
            />
          </div>

          <div className="space-y-2">
            <Label className="text-xs">{t("seoConfig.twitterCardStyle")}</Label>
            <div className="flex gap-3">
              <label className="flex items-center gap-2 text-sm cursor-pointer">
                <input
                  type="radio"
                  name="twitterCard"
                  checked={twitterCard === "summary_large_image"}
                  onChange={() => onTwitterCardChange("summary_large_image")}
                  className="accent-primary"
                />
                {t("seoConfig.largeImage")}
              </label>
              <label className="flex items-center gap-2 text-sm cursor-pointer">
                <input
                  type="radio"
                  name="twitterCard"
                  checked={twitterCard === "summary"}
                  onChange={() => onTwitterCardChange("summary")}
                  className="accent-primary"
                />
                {t("seoConfig.summary")}
              </label>
            </div>
          </div>
        </div>

        {/* Social preview mockup */}
        <div className="rounded-lg border p-4">
          <p className="text-xs text-muted-foreground mb-2">{t("seoConfig.socialPreview")}</p>
          <div className="rounded-lg border overflow-hidden max-w-sm">
            <div className="bg-muted h-32 flex items-center justify-center text-xs text-muted-foreground">
              {t("seoConfig.autoGeneratedOgImage")}
            </div>
            <div className="p-3 space-y-1">
              <p className="text-sm font-semibold truncate">
                {ogTitle || t("seoConfig.ogTitlePlaceholder")}
              </p>
              <p className="text-xs text-muted-foreground line-clamp-2">
                {ogDescription || t("seoConfig.defaultDescription")}
              </p>
            </div>
          </div>
        </div>
      </div>

      <div className="space-y-3">
        <div>
          <Label className="text-sm font-medium">{t("seoConfig.robotsTxtTitle")}</Label>
          <p className="text-xs text-muted-foreground mt-1">
            {t("seoConfig.robotsTxtDescription")}
          </p>
        </div>
        <Textarea
          value={robotsTxtCustom}
          onChange={(e) => onRobotsTxtCustomChange(e.target.value)}
          placeholder="# Additional robots.txt rules
Disallow: /internal/"
          rows={4}
          className="font-mono text-sm"
        />
      </div>
    </div>
  );
}
